data_path: '../data/'
train_data_file: "train.csv"
test_data_file: "test.csv"

model_path: '../model/'
output_dir: '../model/'


train: True
eval: False
test: True
generate: False

task: "prediction_generation" # "hint_generation" # "prediction_generation"

model_name: "meta-llama/Llama-3.2-1B-Instruct" # "../model/beomi/gemma-ko-2b/checkpoint-3654" # "beomi/gemma-ko-2b" # "meta-llama/Llama-3.2-1B-Instruct" # "../model/meta-llama/Llama-3.2-1B-Instruct/checkpoint-3654" # "../model/beomi/gemma-ko-2b/checkpoint-3654" #"maywell/EXAONE-3.0-7.8B-Instruct-Llamafied"
device_map: "auto"
batch_size: 1
num_train_epochs: 2
learning_rate: 0.00002
max_seq_length: 9999
max_new_tokens: 100
use_gptq: False
use_gradient_checkpointing: False
use_mx_fp16: False
use_fp16: True
use_quant: True
use_lora: True
use_hint: True
