documents: []
emb_name: 'skt/kobert-base-v1' # "sentence-transformers/all-mpnet-base-v2"
faiss_folder_path: "../data/faiss_index"

model_name: "../model/Qwen/Qwen2.5-32B-Instruct-GPTQ-Int4/checkpoint-3654"
task: "text-generation"
batch_size: 1
device_map: "auto"
max_new_tokens: 10
use_hint: True
k: 1